// <auto-generated />
using FilmCollection.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmCollection.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    [Migration("20220202043651_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("FilmCollection.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LenTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryId = 6,
                            Director = "Jon Watts",
                            Edited = false,
                            LenTo = "",
                            Notes = "Best movie of 2022",
                            Rating = "PG-13",
                            Title = "Spider-Man: No way home",
                            Year = 2022
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryId = 6,
                            Director = "Kevin Feige",
                            Edited = false,
                            LenTo = "",
                            Notes = "Best movie of 2019",
                            Rating = "PG-13",
                            Title = "Avengers:Endgame",
                            Year = 2019
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryId = 6,
                            Director = "Jon Watts",
                            Edited = false,
                            LenTo = "",
                            Notes = "Best movie of 2018",
                            Rating = "PG-13",
                            Title = "Avengers:Infinity War",
                            Year = 2018
                        });
                });

            modelBuilder.Entity("FilmCollection.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Miscellaneous"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Television"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "VHS"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Action/Adventure"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Drama"
                        });
                });

            modelBuilder.Entity("FilmCollection.Models.ApplicationResponse", b =>
                {
                    b.HasOne("FilmCollection.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
